### ISSUE TITLE
livereload not working

### ISSUE THREAD

**Issue by koraysels** [damassi/sails-js-scaffold#1]
hey man, i've tried your stuff but the livereload is not working. If I change something is scss files I still have to refresh my browser to see the changes ..

**Comment by damassi** [comment]
I'm currently out of town and on a poor internet connection but I'll give it a look when I get back tomorrow.  

(FYI, this is quite out of date with the latest Sails.js release; everything else work ok?)

**Comment by koraysels** [comment]
yeah, i am using sailsjs 9.9 (handlebars branch).. I removed all things related to backbone and gumby, and added bourbon, neat and bitters. Also I am using grunt-browserify as opposed to 
grunt-browserifyv2.. together with browserify 3.46.1 

got everything working, the only that will not work is livereload..

**Comment by damassi** [comment]
Can you point me to the exact Sails.js branch URL you're pulling from?

**Comment by koraysels** [comment]
i don't see what that has todo with the livereload but here it is > https://github.com/tilomitra/sails#handlebars

**Comment by damassi** [comment]
Sorry, v1 of Sails has been significantly refactored so I've kind of abandoned my fork while waiting for them to settle upon a new plugin architecture.  This skel was mostly for the changes that I had proposed via a PR that got lost in the sway, and thus I cannot test.   

I'll pull down this branch and give it a look.

**Comment by damassi** [comment]
For now I would recommend just embedding this snippet in your layout file, and replace the port if you're using something different.  I'm going to close this down since its too divergent from where Sails is going and future maintenance would be trouble.

```
<script src="http://192.168.0.1:35729/livereload.js?snipver=1"></script>
```

**Comment by koraysels** [comment]
Cool, I'll check it out. Thanks, i knew it was an old repo;) np
